on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
                  genisoimage \
                  libkrb5-dev \
                  libvirt-daemon-system \
                  libvirt-dev \
                  pkg-config \
                  podman \
                  qemu-kvm \
              -y

      - name: Install tmt from PyPi
        run: |
          # Remove when https://github.com/teemtee/tmt/pull/1930 is released in tmt 1.22
          pip install git+https://github.com/teemtee/tmt.git@main
          pip install "tmt[provision]" "tmt[report-junit]"

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Use githash of a tested commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        run: |
          tmt run

      - name: Export tests output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /var/tmp/tmt
